doc = """Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Valentin Volkl 28.07.2013"""


import sys
import numpy as np

try:
	n = int(sys.argv[1])
except:
	n = 4e6
d = 0
a = 1
b = 1

while(a < n and b < n):
	a = a + b
	if (a % 2 == 0):
		d = d + a
	b = a + b
	if (a % 2 == 0):
		d = d + b

print 'solution:', d
